//! Built-in release optimization descriptors.

use super::optimization_registry::OptimizationPass;

macro_rules! pass {
    ($id:literal, $owner:literal, $phase:literal, $invariant:literal, $benchmark:literal) => {
        OptimizationPass {
            id: $id,
            owner: $owner,
            phase: $phase,
            invariant: $invariant,
            benchmark: $benchmark,
        }
    };
}

/// Built-in release optimization descriptors.
pub const RELEASE_OPTIMIZATION_PASSES: &[OptimizationPass] = &[
    pass!("cuda.pinned-readback-pool", "vyre-cuda", "cuda-resident-io", "D2H slots preserve caller output capacity", "resident_dispatch_contracts"),
    pass!("cuda.pinned-param-upload", "vyre-cuda", "cuda-launch", "parameter blocks upload once per unique launch shape", "resident_dispatch_contracts"),
    pass!("cuda.resolved-launch-hoist", "vyre-cuda", "cuda-launch", "function and handle resolution stay outside repeated loops", "resident_dispatch_contracts"),
    pass!("cuda.graph-replay-cache", "vyre-cuda", "cuda-graph", "graph exec replay matches direct dispatch outputs", "cuda_graph_dispatch_parity"),
    pass!("cuda.module-cache", "vyre-cuda", "cuda-jit", "same PTX module loads once per backend session", "module_cache_contracts"),
    pass!("cuda.transient-allocation-pool", "vyre-cuda", "cuda-memory", "same-shape dispatch reuses transient device allocations", "module_cache_contracts"),
    pass!("cuda.launch-resource-cache", "vyre-cuda", "cuda-launch", "same-shape dispatch reuses launch resource buffers", "module_cache_contracts"),
    pass!("cuda.telemetry-scheduler-sample", "vyre-cuda", "megakernel-scheduler", "runtime telemetry maps to bounded frontier density", "telemetry_contracts"),
    pass!("cuda.megakernel-topology-select", "vyre-cuda", "megakernel-scheduler", "topology derives from density graph shape and memory pressure", "megakernel_scale_scheduler_contracts"),
    pass!("cuda.megakernel-plan-cache", "vyre-cuda", "megakernel-cache", "graph analysis device pressure buckets isolate cached plans", "megakernel_plan_cache"),
    pass!("cuda.megakernel-memory-budget", "vyre-cuda", "megakernel-memory", "peak bytes are bounded before launch", "megakernel_scheduler"),
    pass!("cuda.megakernel-speedup-gate", "vyre-cuda", "benchmark", "steady-state resident megakernel samples prove 100x plus speedup without setup pollution", "megakernel_speedup_gate"),
    pass!("cuda.megakernel-barrier-min", "vyre-cuda", "megakernel-scheduler", "dependency DAG layers minimize global barriers", "megakernel_barrier_planner"),
    pass!("cuda.frontier-execution-plan", "vyre-cuda", "megakernel-scheduler", "frontier waves combine barrier and memory planning", "megakernel_barrier_planner"),
    pass!("cuda.warp-sparse-frontier", "vyre-cuda", "megakernel-scheduler", "ultra-low-density frontiers avoid block-wide sparse dispatch waste", "megakernel_scheduler"),
    pass!("cuda.block-dense-frontier", "vyre-cuda", "megakernel-scheduler", "high-density frontiers use block-coalesced shared-memory propagation", "megakernel_scheduler"),
    pass!("cuda.sparse-frontier-queue", "vyre-cuda", "graph-traversal", "sparse queue traversal avoids selector readback", "csr_frontier_queue_gpu_parity"),
    pass!("cuda.resident-csr-queue-api", "vyre-cuda", "graph-traversal", "CSR graph buffers upload once across sparse queries", "csr_frontier_queue_gpu_parity"),
    pass!("cuda.resident-csr-queue-batch-api", "vyre-cuda", "graph-traversal", "many CSR frontier queries share graph residency and one host fence", "csr_frontier_queue_gpu_parity"),
    pass!("cuda.resident-csr-batch-memory-plan", "vyre-cuda", "graph-traversal", "resident CSR query batches shard before exceeding scratch budget", "csr_frontier_queue_batch_resident"),
    pass!("cuda.device-side-convergence", "vyre-cuda", "megakernel-scheduler", "iterative dataflow reads final changed flag only", "megakernel_convergence"),
    pass!("cuda.device-work-queue", "vyre-cuda", "megakernel-scheduler", "dependent dataflow drains resident work queues without host participation", "device_work_queue"),
    pass!("cuda.device-diagnostic-aggregation", "vyre-cuda", "diagnostics", "diagnostics compact on device before bounded final-only host readback", "device_diagnostic_aggregation"),
    pass!("cuda.multi-query-resident-execution", "vyre-cuda", "megakernel-scheduler", "many analyses over one resident graph share upload traversal setup launch and host fence cost", "multi_query_execution"),
    pass!("cuda.resident-graph-session", "vyre-cuda", "cuda-resident-sequence", "fixed graph topology uploads once and repeated execution reuses scratch with final-only readback", "resident_graph_session"),
    pass!("cuda.adjacent-launch-fusion", "vyre-cuda", "cuda-launch", "adjacent compatible dataflow stages fuse without host-visible intermediate materialization", "launch_fusion"),
    pass!("cuda.fixed-graph-replay", "vyre-cuda", "cuda-resident-sequence", "repeat count grows without extra host fences or readback", "resident_dispatch_contracts"),
    pass!("cuda.compact-read-ranges", "vyre-cuda", "cuda-resident-io", "readback transfers only requested ranges", "resident_dispatch_contracts"),
    pass!("cuda.result-compaction", "vyre-cuda", "cuda-resident-io", "small outputs compact into one meaningful-byte readback slab", "result_compaction"),
    pass!("cuda.benchmark-pass-selection", "vyre-cuda", "optimizer", "expensive CUDA optimizations fire only when benchmark-derived graph frontier reuse and readback thresholds justify them", "benchmark_pass_selection"),
    pass!("cuda.borrowed-output-slots", "vyre-cuda", "cuda-resident-io", "readbacks materialize into caller-owned Vec slots", "resident_dispatch_contracts"),
    pass!("cuda.grid-sync-capability-gate", "vyre-cuda", "cuda-launch", "cooperative kernels require explicit device support", "cooperative_launch_contracts"),
    pass!("cuda.kernel-failure-diagnostics", "vyre-cuda", "cuda-launch", "kernel launch failures report every missing CUDA capability with an actionable fix", "kernel_failure_diagnostics"),
    pass!("cuda.occupancy-autotune", "vyre-cuda", "cuda-launch", "workgroup selection respects device occupancy caps", "i3_i4_integration"),
    pass!("vyre.preferred-cuda-backend", "vyre-driver", "dispatch-routing", "linked CUDA outranks reference oracles", "preferred_dispatch_backend"),
    pass!("vyre.no-host-devicebuffer-shim", "vyre-driver", "dispatch-routing", "DeviceBuffer dispatch cannot hide host staging escape paths", "device_buffer"),
    pass!("vyre.pipeline-modularity", "vyre-driver", "pipeline", "pipeline only orchestrates stage duties", "pipeline_modularity_contract"),
    pass!("vyre.public-api-boundary", "vyre-driver", "api", "public APIs hide staging buffers temporary graph encodings and pipeline internals", "public_api_boundary"),
    pass!("vyre.contributor-module-map", "vyre-driver", "architecture", "contributors can find the one module family for kernels analyses parser phases diagnostics benchmarks and validation", "contributor_module_map"),
    pass!("vyre.output-slot-reuse", "vyre-driver", "pipeline", "compiled dispatch reuses caller output slots", "pipeline"),
    pass!("vyre.shape-prediction", "vyre-driver", "dispatch-routing", "launch shape prediction avoids host wait gaps", "shape_prediction"),
    pass!("vyre.device-extraction", "vyre-driver", "dispatch-routing", "device-conditioned choices are explicit", "device_extraction"),
    pass!("vyre.architecture-boundary-map", "vyre-driver", "architecture", "Vyre Dataflow consumer and Vyrec duties have one explicit owner and module boundary", "architecture_boundary_map"),
    pass!("vyre.memory-ownership-contract", "vyre-driver", "memory", "host caller device resident pinned staging borrowed output and parity memory boundaries are explicit", "memory_ownership_contract"),
    pass!("vyre.strategy-specialization", "vyre-driver", "lowering", "specialized lowering returns nonfallback variant ids", "specialization"),
    pass!("vyre.cross-grid-split", "vyre-driver", "lowering", "grid-sync split preserves cross-kernel dependencies", "cooperative_launch_contracts"),
    pass!("vyre.aot-launcher-manifest", "vyre-driver", "aot", "launcher dependencies remain explicit", "aot_launcher_contracts"),
    pass!("vyre.binding-plan-verify", "vyre-driver", "binding", "resource bindings match static byte contracts", "binding_plan_contracts"),
    pass!("dataflow.fixed-point-resident-graph", "dataflow", "dataflow-residency", "invariant graph buffers upload once", "fixed_point_resident"),
    pass!("dataflow.resident-graph-cache", "dataflow", "dataflow-residency", "equivalent normalized layouts reuse resident graph", "fixed_point_resident_cache"),
    pass!("dataflow.resident-family-check", "dataflow", "dataflow-safety", "analysis cannot consume wrong resident graph family", "fixed_point_resident"),
    pass!("dataflow.resident-frontier-reuse", "dataflow", "dataflow-residency", "frontier handles reuse capacity across runs", "fixed_point_resident"),
    pass!("dataflow.resident-batch", "dataflow", "dataflow-batch", "multiple analyses share graph residency and frontier scratch", "fixed_point_resident_batch"),
    pass!("dataflow.execution-plan-cache", "dataflow", "dataflow-planning", "execution plans are keyed by graph family and budget", "fixed_point_execution_plan_cache"),
    pass!("dataflow.graph-layout-hash", "dataflow", "graph-layout", "equivalent CSR graphs produce stable hashes", "fixed_point_graph"),
    pass!("dataflow.graph-normalization", "dataflow", "graph-layout", "duplicate and unsorted edges normalize deterministically", "fixed_point_graph"),
    pass!("dataflow.shared-graph-layout-coverage", "dataflow", "graph-layout", "dominators callgraph IFDS slicing and range propagation use shared layout compatibility checks", "graph_layout_coverage"),
    pass!("dataflow.ifds-direct-resident-csr", "dataflow", "ifds-residency", "exploded CSR is cached for repeated IFDS solves", "ifds_direct_resident_structure"),
    pass!("dataflow.ifds-parallel-single-step", "dataflow", "ifds-solve", "parallel IFDS reuses one batch step program", "ifds_direct_resident_structure"),
    pass!("dataflow.ifds-final-flag-readback", "dataflow", "ifds-solve", "parallel IFDS reads final changed flag only", "ifds_gpu_solve_gpu_parity"),
    pass!("dataflow.ifds-repeated-sequence", "dataflow", "ifds-solve", "fixed-point loops use repeated resident sequence API", "ifds_gpu_solve_gpu_parity"),
    pass!("dataflow.ifds-result-slots", "dataflow", "ifds-solve", "result Vec slots retain capacity", "ifds_resident_download_scratch_contract"),
    pass!("dataflow.reaching-resident-frontier", "dataflow", "reaching", "reaching closure reuses resident frontier buffers", "fixed_point_resident"),
    pass!("dataflow.live-resident-frontier", "dataflow", "live", "live closure reuses resident frontier buffers", "fixed_point_resident"),
    pass!("dataflow.points-to-resident-frontier", "dataflow", "points-to", "points-to closure reuses resident frontier buffers", "fixed_point_resident"),
    pass!("dataflow.slice-resident-frontier", "dataflow", "slice", "slice closure reuses resident frontier buffers", "fixed_point_resident"),
    pass!("dataflow.output-scratch", "dataflow", "dataflow-output", "analysis outputs reuse caller-owned scratch", "output_scratch_contract"),
    pass!("dataflow.dispatch-input-cache", "dataflow", "dataflow-dispatch", "stable inputs reuse encoded byte buffers", "dispatch_input_cache"),
    pass!("dataflow.bitset-tail-validation", "dataflow", "dataflow-safety", "unused tail bits remain clear", "df_property_bitset_oracles"),
    pass!("dataflow.monotonicity-checks", "dataflow", "dataflow-safety", "closures preserve lattice monotonicity", "df_property_reaching_def_escapes"),
    pass!("dataflow.join-associativity", "dataflow", "dataflow-safety", "lattice joins remain associative", "df_property_bitset_oracles"),
    pass!("dataflow.adversarial-graphs", "dataflow", "dataflow-tests", "empty fanout fanin cycle and disconnected graphs are covered", "df_adversarial_oracles"),
    pass!("dataflow.gpu-parity-inventory", "dataflow", "dataflow-tests", "GPU primitives match explicit oracle tests", "df_parity_inventory_sweep"),
    pass!("dataflow.analysis-coverage", "dataflow", "dataflow-tests", "reaching liveness points-to slicing and IFDS have scratch residency property adversarial and allocation evidence", "analysis_coverage"),
    pass!("dataflow.benchmark-hot-graph", "dataflow", "dataflow-benchmark", "hot resident benchmarks exclude graph upload", "resident_benchmark_contract"),
    pass!("vyrec.beta-release-docs", "vyrec", "frontend-release", "beta scope does not hide parser or semantic gaps", "release docs"),
    pass!("release.scope-docs", "release", "release-gate", "stable Vyre and Dataflow consumer capabilities are separated from Vyrec beta lower-step scope", "release_scope_docs"),
    pass!("vyrec.dialect-matrix", "vyrec", "frontend-release", "supported C phases are explicit and unsupported beta scope is lower-step only", "c_dialect_matrix"),
    pass!("vyrec.gpu-token-classify", "vyrec", "preprocessing", "token classes preserve byte provenance", "preprocessor gpu parity"),
    pass!("vyrec.gpu-preprocessing-coverage", "vyrec", "preprocessing", "GPU preprocessing covers macros includes provenance line markers and all token classes", "gpu_preprocessing_coverage"),
    pass!("vyrec.macro-prefilter", "vyrec", "preprocessing", "identifier mentions are not rescanned as macro calls", "macro prefilter tests"),
    pass!("vyrec.include-cache-residency", "vyrec", "preprocessing", "unchanged includes avoid re-tokenize or re-upload", "include cache tests"),
    pass!("vyrec.token-provenance", "vyrec", "diagnostics", "macro-expanded tokens retain source provenance", "diagnostic provenance tests"),
    pass!("vyrec.diagnostic-comparison", "vyrec", "diagnostics", "diagnostics compare location severity category and primary message class against clang", "diagnostic_comparison"),
    pass!("vyrec.line-marker-tracking", "vyrec", "preprocessing", "line markers map diagnostics to original files", "clang diagnostic diff"),
    pass!("vyrec.stringification", "vyrec", "preprocessing", "stringification preserves clang token spelling", "clang macro parity"),
    pass!("vyrec.token-pasting", "vyrec", "preprocessing", "token pasting matches clang token boundaries", "clang macro parity"),
    pass!("vyrec.variadic-macros", "vyrec", "preprocessing", "variadic macro expansion matches clang", "clang macro parity"),
    pass!("vyrec.builtin-macros", "vyrec", "preprocessing", "builtin macros are phase-stable and provenance-tagged", "clang macro parity"),
    pass!("vyrec.parser-recovery", "vyrec", "parsing", "malformed code emits diagnostics without fake AST success", "parser recovery tests"),
    pass!("vyrec.parser-semantic-safety", "vyrec", "frontend-tests", "parser recovery and semantic invariant rejection cases have cargo_full evidence", "parser_semantic_safety"),
    pass!("vyrec.semantic-decls", "vyrec", "semantic-analysis", "declarations and scopes match clang", "clang semantic diff"),
    pass!("vyrec.semantic-typedefs", "vyrec", "semantic-analysis", "typedef and tag namespaces are separated", "clang semantic diff"),
    pass!("vyrec.semantic-conversions", "vyrec", "semantic-analysis", "integer promotions and usual conversions match clang", "clang semantic diff"),
    pass!("vyrec.semantic-lvalues", "vyrec", "semantic-analysis", "lvalue/rvalue rules reject impossible states", "semantic invariant tests"),
    pass!("vyrec.semantic-parity-coverage", "vyrec", "semantic-analysis", "all required C semantic categories have explicit cargo_full clang parity evidence", "semantic_parity_coverage"),
    pass!("vyrec.linux-corpus-diff", "vyrec", "frontend-tests", "Linux subsystem slices have clang oracle commands fixture provenance and cargo_full Vyrec parity evidence", "linux_corpus_parity"),
    pass!("vyrec.corpus-minimizer", "vyrec", "frontend-tests", "clang mismatches minimize to reproducible fixtures", "linux_corpus_parity"),
    pass!("vyrec.clang-parity-dashboard", "vyrec", "frontend-tests", "clang-compatible partial and failing C features are visible with cargo_full evidence", "clang_parity_dashboard"),
    pass!("vyrec.directive-fuzz", "vyrec", "frontend-fuzz", "preprocessor directives survive hostile fuzz input", "preprocessor fuzz"),
    pass!("vyrec.huge-file-oom", "vyrec", "frontend-fuzz", "huge files fail loudly without truncation", "huge file adversarial tests"),
    pass!("struct.device-resident-token-fact-graph", "vyre-self", "optimizer", "parser semantic diagnostic and dataflow nodes share one resident token/fact CSR layout", "device_resident_token_fact_graph"),
    pass!("struct.incremental-invalidation", "vyre-self", "optimizer", "source edits recompute only changed token macro semantic and fact regions", "incremental_invalidation"),
    pass!("struct.frontier-partitioning", "vyre-self", "optimizer", "conflicting frontier updates are color-partitioned before shared-node CUDA writes", "frontier_partitioning"),
    pass!("struct.frontier-typed-ir", "vyre-self", "optimizer", "parser semantic diagnostic and dataflow work become explicit dependency waves", "frontier_typed_ir"),
    pass!("struct.multi-corpus-batching", "vyre-self", "optimizer", "translation units share include preprocessing and semantic residency by stable batch key", "multi_corpus_batching"),
    pass!("struct.branch-compaction", "vyre-self", "optimizer", "zero-lane predicate arms are removed and launch parameters are packed before CUDA execution", "branch_compaction"),
    pass!("struct.bitset-compression", "vyre-self", "optimizer", "low-density dataflow fact bitsets use sparse CUDA index payloads instead of dense words", "bitset_compression"),
    pass!("cuda.token-fact-graph-layout-adapter", "vyre-cuda", "megakernel-scheduler", "unified token/fact graph layouts adapt into CUDA resident byte envelopes", "token_fact_graph_cuda_adapter"),
    pass!("cuda.token-fact-frontier-execution", "vyre-cuda", "megakernel-scheduler", "frontier-typed token/fact graphs plan dependency-aware CUDA megakernel execution", "token_fact_frontier_execution"),
    pass!("cuda.frontier-typed-ir-adapter", "vyre-cuda", "megakernel-scheduler", "frontier-typed compiler waves adapt into CUDA frontier byte envelopes", "frontier_typed_ir_adapter"),
    pass!("self.dce-resident", "vyre-self", "optimizer", "DCE keeps live stores and removes dead lets", "self_optimizer_e2e"),
    pass!("self.const-fold", "vyre-self", "optimizer", "constant folding preserves expression value", "self_optimizer_const_fold_extended"),
    pass!("self.const-prop", "vyre-self", "optimizer", "constant propagation never lengthens optimized body", "self_optimizer_const_prop_e2e"),
    pass!("self.cse", "vyre-self", "optimizer", "common subexpressions share canonical value", "self_optimizer_cse_e2e"),
    pass!("self.cross-scope-cse", "vyre-self", "optimizer", "CSE respects lexical scope boundaries", "self_optimizer_cross_scope_cse_e2e"),
    pass!("self.licm", "vyre-self", "optimizer", "loop invariant code moves without changing loop effects", "self_optimizer_licm_e2e"),
    pass!("self.pattern-match", "vyre-self", "optimizer", "pattern rewrites preserve matched semantics", "self_optimizer_pattern_match_extended"),
    pass!("self.pipeline-resident", "vyre-self", "optimizer", "optimizer pipeline keeps arena resident across passes", "self_optimizer_pipeline_resident_e2e"),
    pass!("self.validate", "vyre-self", "optimizer", "validator rejects impossible optimized IR states", "self_optimizer_validate_e2e"),
    pass!("self.differential", "vyre-self", "optimizer", "GPU optimizer is at least as aggressive as CPU DCE oracle", "self_optimizer_differential"),
    pass!("primitive.bitset-and", "vyre-primitives", "bitset", "AND preserves bitset width and tail bits", "bitset_primitives_gpu_parity"),
    pass!("primitive.bitset-or", "vyre-primitives", "bitset", "OR preserves bitset width and tail bits", "bitset_primitives_gpu_parity"),
    pass!("primitive.bitset-xor", "vyre-primitives", "bitset", "XOR preserves bitset width and tail bits", "bitset_primitives_gpu_parity"),
    pass!("primitive.bitset-popcount", "vyre-primitives", "bitset", "popcount matches packed bit cardinality", "bitset_popcount_gpu_parity"),
    pass!("primitive.prefix-scan", "vyre-primitives", "math", "scan order matches inclusive/exclusive contract", "math_primitives_gpu_parity"),
    pass!("primitive.stream-compact", "vyre-primitives", "math", "compaction emits flagged payloads only", "math_primitives_gpu_parity"),
    pass!("primitive.csr-forward", "vyre-primitives", "graph", "CSR forward traversal respects edge masks", "csr_forward_or_changed_gpu_parity"),
    pass!("primitive.csr-backward", "vyre-primitives", "graph", "CSR backward traversal respects reverse edges", "csr_backward_traverse_gpu_parity"),
    pass!("primitive.csr-bidirectional", "vyre-primitives", "graph", "bidirectional traversal preserves source/target symmetry", "csr_bidirectional_gpu_parity"),
    pass!("primitive.adaptive-traverse", "vyre-primitives", "graph", "adaptive sparse/dense traversal avoids selector readback", "adaptive_traverse_vast_walk_gpu_parity"),
    pass!("primitive.persistent-bfs", "vyre-primitives", "graph", "persistent BFS reuses resident graph queries", "persistent_bfs_gpu_parity"),
    pass!("primitive.dominator-frontier", "vyre-primitives", "graph", "dominance frontier matches graph dominance invariant", "dominator_frontier_gpu_parity"),
    pass!("primitive.scc", "vyre-primitives", "graph", "SCC decomposition partitions nodes exactly once", "scc_decompose_gpu_parity"),
    pass!("primitive.union-find", "vyre-primitives", "graph", "union-find produces stable representatives", "union_find_gpu_parity"),
    pass!("primitive.reduce-array", "vyre-primitives", "reduce", "array reductions match oracle outputs", "reduce_array_primitives_gpu_parity"),
    pass!("primitive.reduce-scalar", "vyre-primitives", "reduce", "scalar reductions match oracle outputs", "reduce_scalar_primitives_gpu_parity"),
    pass!("primitive.text-classify", "vyre-primitives", "text", "text primitives preserve byte/class counts", "text_primitives_gpu_parity"),
    pass!("primitive.hash-parsing", "vyre-primitives", "hash", "hash parsing primitives are deterministic", "hash_parsing_primitives_gpu_parity"),
    pass!("primitive.encoding-classify", "vyre-primitives", "encoding", "encoding classes match byte histogram shape", "encoding_classify_gpu_parity"),
    pass!("primitive.tensor-scc", "vyre-primitives", "tensor", "tensor SCC preserves component reachability", "tensor_scc_gpu_parity"),
    pass!("primitive.semiring-gemm", "vyre-primitives", "math", "semiring GEMM preserves algebraic product", "semiring_gemm_gpu_parity"),
    pass!("primitive.four-russians", "vyre-primitives", "math", "Four Russians blocks preserve dense closure", "four_russians_gpu_parity"),
    pass!("primitive.sketch-sparse-fft", "vyre-primitives", "hash", "sketch and sparse FFT hashes match oracle bins", "sketch_sparse_fft_gpu_parity"),
    pass!("release.deep-test-matrix", "release", "release-gate", "Vyre Dataflow consumer Vyrec gates use cargo_full and GPU probes", "release test matrix"),
    pass!("release.test-taxonomy-coverage", "release", "release-gate", "major modules have unit adversarial property benchmark fuzz and gap evidence", "test_taxonomy_coverage"),
    pass!("release.hostile-input-coverage", "release", "release-gate", "invalid bytes nesting include cycles recursive macros massive graphs and corrupted cache metadata have hostile tests", "hostile_input_coverage"),
    pass!("release.cpu-fallback-ban", "release", "release-gate", "production dispatch cannot reach CPU reference or oracle modules", "cpu_fallback_reachability"),
    pass!("release.gpu-probe-contract", "release", "release-gate", "GPU gates use loud probe failures and never skip silently on no GPU", "gpu_probe_contract"),
    pass!("release.allocation-regression", "release", "release-gate", "hot loops allocate nothing after warmup and preserve output slot capacity", "allocation_regression"),
    pass!("release.benchmark-baselines", "release", "release-gate", "performance claims map to committed CUDA thresholds and cargo_full commands", "benchmark_baselines"),
    pass!("release.public-api-doctests", "release", "release-gate", "public examples compile against real APIs and never expose internals", "public_api_doctest_gate"),
    pass!("release.gpu-evidence", "release", "release-gate", "release artifacts record nvidia-smi CUDA hardware driver and cargo_full commands", "release_gpu_evidence"),
    pass!("release.gap-findings", "release", "release-gate", "missing clang or dataflow parity is tracked as reproducible gap findings instead of silent green evidence", "release_gap_findings"),
    pass!("release.checklist-green", "release", "release-gate", "cargo_full GPU fuzz gap benchmarks docs metadata public API and deep review evidence are all green", "release_checklist_gate"),
    pass!("release.launch-sequence", "release", "release-gate", "final release order is cargo_full green then cargo_full publish then public repos then git push and tags", "release_launch_sequence"),
    pass!("release.crate-metadata-readiness", "release", "release-gate", "public crates have complete package metadata real code and exact cargo_full publish commands", "crate_metadata_readiness"),
    pass!("release.deep-personal-review", "release", "release-gate", "every touched public crate file is read in full and every review finding is fixed", "deep_review_gate"),
];
