//! Lowering from structural parse (VAST) to packed graph (PG) nodes.
//!
//! Production lowering is GPU IR generation. CPU reference paths are retained
//! only as explicit parity oracles and test fixtures.

/// AST to PG nodes lowering pass.
pub mod ast_to_pg_nodes;
mod semantic_edges;

#[allow(deprecated)]
pub use ast_to_pg_nodes::{
    c_lower_ast_to_pg_nodes, c_lower_ast_to_pg_semantic_graph, PgReferenceDecodeError,
    SemanticPgReference, C_AST_PG_CATEGORY_CONTROL, C_AST_PG_CATEGORY_DECLARATION,
    C_AST_PG_CATEGORY_EXPRESSION, C_AST_PG_CATEGORY_GNU, C_AST_PG_CATEGORY_NONE,
    C_AST_PG_EDGE_CASE_VALUE, C_AST_PG_EDGE_FIRST_CHILD, C_AST_PG_EDGE_GOTO_TARGET,
    C_AST_PG_EDGE_NEXT_SIBLING, C_AST_PG_EDGE_NONE, C_AST_PG_EDGE_PARENT,
    C_AST_PG_EDGE_ROWS_PER_NODE, C_AST_PG_EDGE_STRIDE_U32, C_AST_PG_EDGE_SWITCH_CASE,
    C_AST_PG_EDGE_SWITCH_DEFAULT, C_AST_PG_EDGE_SWITCH_SELECTOR, C_AST_PG_ROLE_AGGREGATE_DECL,
    C_AST_PG_ROLE_ALIGNOF, C_AST_PG_ROLE_ARRAY_DECL, C_AST_PG_ROLE_ARRAY_DESIGNATOR_OR_SUBSCRIPT,
    C_AST_PG_ROLE_ASM_CLOBBER, C_AST_PG_ROLE_ASM_GOTO_LABEL, C_AST_PG_ROLE_ASM_INPUT,
    C_AST_PG_ROLE_ASM_OUTPUT, C_AST_PG_ROLE_ASM_QUALIFIER, C_AST_PG_ROLE_ASM_TEMPLATE,
    C_AST_PG_ROLE_ASSIGNMENT, C_AST_PG_ROLE_BIT_FIELD_DECL, C_AST_PG_ROLE_BREAK,
    C_AST_PG_ROLE_CASE, C_AST_PG_ROLE_CONTINUE, C_AST_PG_ROLE_DECLARATION, C_AST_PG_ROLE_DEFAULT,
    C_AST_PG_ROLE_ENUMERATOR_DECL, C_AST_PG_ROLE_EXPRESSION, C_AST_PG_ROLE_FIELD_DECL,
    C_AST_PG_ROLE_FIELD_DESIGNATOR_OR_MEMBER_ACCESS, C_AST_PG_ROLE_FUNCTION_DECLARATOR,
    C_AST_PG_ROLE_FUNCTION_DEFINITION, C_AST_PG_ROLE_FUNCTION_POINTER_DECL,
    C_AST_PG_ROLE_GNU_ATTRIBUTE, C_AST_PG_ROLE_GNU_ATTRIBUTE_DETAIL, C_AST_PG_ROLE_GOTO,
    C_AST_PG_ROLE_INITIALIZER_LIST, C_AST_PG_ROLE_INLINE_ASM, C_AST_PG_ROLE_LABEL,
    C_AST_PG_ROLE_LOOP, C_AST_PG_ROLE_NONE, C_AST_PG_ROLE_POINTER_DECL,
    C_AST_PG_ROLE_RANGE_DESIGNATOR, C_AST_PG_ROLE_RETURN, C_AST_PG_ROLE_SELECTION,
    C_AST_PG_ROLE_STATEMENT_EXPR, C_AST_PG_ROLE_STATIC_ASSERT_DECL, C_AST_PG_ROLE_SWITCH,
    C_AST_PG_ROLE_TYPEDEF_DECL, C_AST_PG_ROLE_UNREACHABLE, C_AST_PG_SEMANTIC_NODE_STRIDE_U32,
};
#[allow(deprecated)]
#[cfg(any(test, feature = "cpu-parity"))]
pub use ast_to_pg_nodes::{
    reference_ast_to_pg_nodes, reference_ast_to_pg_semantic_graph, try_reference_ast_to_pg_nodes,
    try_reference_ast_to_pg_semantic_graph,
};
