//! Rust launcher source generator.
//!
//! `vyre-aot` owns the target-neutral package shell. Concrete driver crates
//! own every target-specific launcher file through `vyre-driver`'s AOT
//! launcher registry.

use std::collections::BTreeMap;
use std::path::PathBuf;

use thiserror::Error;
use vyre_driver::aot::{AotLauncherRequest, LauncherDependency};

use crate::artifact::CompiledArtifact;

/// Options controlling launcher emission.
#[derive(Debug, Clone)]
pub struct LauncherOpts {
    /// Crate name (becomes the binary name on disk).
    pub crate_name: String,
    /// Whether to enable target-owned multi-rank collective support.
    pub include_collectives: bool,
    /// Whether to enable a built-in TTT loop (eval-time SGD over chunks).
    /// If `false`, eval is delegated to a separate launcher invocation.
    pub include_ttt_loop: bool,
}

impl Default for LauncherOpts {
    fn default() -> Self {
        Self {
            crate_name: "pgolf-launcher".to_string(),
            include_collectives: true,
            include_ttt_loop: false,
        }
    }
}

/// Error variants returned by [`emit_launcher_rust`].
#[derive(Debug, Error)]
pub enum LauncherError {
    /// No linked driver owns launcher generation for the artifact target.
    #[error("vyre-aot launcher: target {0} has no linked launcher emitter")]
    TargetNotEnabled(&'static str),

    /// The target-owned launcher emitter rejected the request.
    #[error("vyre-aot launcher: target emitter failed: {0}")]
    Backend(String),
}

/// Emit the Rust launcher source tree.
///
/// Returns a map from relative file path to file contents. The caller writes
/// each entry to disk under the launcher crate root.
///
/// # Errors
///
/// Returns [`LauncherError::TargetNotEnabled`] when the artifact target has
/// no linked launcher emitter, or [`LauncherError::Backend`] when that emitter
/// rejects the request.
pub fn emit_launcher_rust(
    artifact: &CompiledArtifact,
    opts: &LauncherOpts,
) -> Result<BTreeMap<PathBuf, String>, LauncherError> {
    let target = artifact.target.aot_target_id();
    let request = AotLauncherRequest {
        target,
        crate_name: &opts.crate_name,
        include_collectives: opts.include_collectives,
        include_ttt_loop: opts.include_ttt_loop,
    };

    let target_files = vyre_driver::aot::emit_aot_launcher_target(target, &request).map_err(
        |error| match error {
            vyre_driver::BackendError::UnsupportedFeature { .. } => {
                LauncherError::TargetNotEnabled(target)
            }
            other => LauncherError::Backend(other.to_string()),
        },
    )?;

    let mut tree = target_files.files;
    tree.insert(
        PathBuf::from("Cargo.toml"),
        emit_launcher_cargo_toml(opts, &target_files.dependencies),
    );
    tree.insert(
        PathBuf::from(".cargo/config.toml"),
        EMIT_CARGO_BUILD_CONFIG.to_string(),
    );
    tree.insert(
        PathBuf::from("src/artifact.rs"),
        EMIT_ARTIFACT_LOADER.to_string(),
    );
    tree.insert(PathBuf::from("README.md"), emit_launcher_readme(opts));

    Ok(tree)
}

fn emit_launcher_cargo_toml(opts: &LauncherOpts, deps: &[LauncherDependency]) -> String {
    let mut dependencies = String::from(
        r#"[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
brotli = "8"
lzma-rs = "0.3"
sha2 = "0.10"
"#,
    );
    for dep in deps {
        dependencies.push_str(dep.name);
        dependencies.push_str(" = ");
        dependencies.push_str(dep.spec);
        dependencies.push('\n');
    }

    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false

{dependencies}
[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false
debug-assertions = false
incremental = false

[[bin]]
name = "{name}"
path = "src/main.rs"
"#,
        name = opts.crate_name,
        dependencies = dependencies,
    )
}

const EMIT_CARGO_BUILD_CONFIG: &str = r#"# Size-optimized launcher build flags.
[build]
rustflags = ["-C", "relocation-model=pic", "-C", "embed-bitcode=yes"]
"#;

const EMIT_ARTIFACT_LOADER: &str = include_str!("../templates/artifact.rs.tmpl");

fn emit_launcher_readme(opts: &LauncherOpts) -> String {
    let collective_status = if opts.include_collectives {
        "enabled"
    } else {
        "disabled"
    };
    format!(
        r#"# {name}

Auto-generated by `vyre-aot`. Self-contained target launcher for a vyre-emitted
persistent kernel.

## Build

```
./cargo_full build --release
```

The release binary is heavily size-optimized:
`opt-level=z`, `lto=fat`, `codegen-units=1`, `panic=abort`, `strip=symbols`.

## Run

```
{name} <bundle_dir>
```

Reads `manifest.json`, `kernel.<ext>.lzma`, and `weights.brotli` from the
bundle directory. Allocates buffers, uploads weights, launches the kernel,
and prints the final metrics record on completion.

Target-owned collective support is {collective_status} in this launcher.
"#,
        name = opts.crate_name,
        collective_status = collective_status,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emitted_launcher_declares_sha2_for_runtime_integrity_checks() {
        let opts = LauncherOpts::default();
        let cargo = emit_launcher_cargo_toml(&opts, &[]);

        assert!(
            cargo.contains("sha2 = \"0.10\""),
            "Fix: generated launchers must include sha2 so runtime artifact integrity checks compile."
        );
    }

    #[test]
    fn emitted_artifact_loader_verifies_payload_hashes_and_rejects_path_escape() {
        assert!(
            EMIT_ARTIFACT_LOADER.contains("verify_sha256_hex(")
                && EMIT_ARTIFACT_LOADER.contains("SHA-256 mismatch"),
            "Fix: generated launchers must verify decompressed kernel and weight bytes before CUDA load/upload."
        );
        assert!(
            EMIT_ARTIFACT_LOADER.contains("validate_bundle_relative_path")
                && EMIT_ARTIFACT_LOADER.contains("Component::ParentDir"),
            "Fix: generated launchers must reject manifest paths that escape the bundle root."
        );
        assert!(
            EMIT_ARTIFACT_LOADER.contains("read_bundle_file(dir, &manifest.kernel_file)")
                && EMIT_ARTIFACT_LOADER.contains("read_bundle_file(dir, &manifest.weights_file)"),
            "Fix: generated launchers must route artifact reads through the validated bundle path helper."
        );
    }

    #[test]
    fn emitted_artifact_loader_preflights_manifest_contract_before_cuda_runtime_work() {
        assert!(
            EMIT_ARTIFACT_LOADER.contains("validate_manifest_contract(&manifest)?")
                && EMIT_ARTIFACT_LOADER.contains("MANIFEST_SCHEMA_VERSION")
                && EMIT_ARTIFACT_LOADER.contains("vyre-aot-manifest-v1"),
            "Fix: generated launchers must reject incompatible manifest schemas before reading payloads."
        );
        assert!(
            EMIT_ARTIFACT_LOADER.contains("validate_dispatch_geometry(&manifest.dispatch)")
                && EMIT_ARTIFACT_LOADER.contains("runtime-grid placeholders are not supported"),
            "Fix: generated launchers must reject zero dispatch axes before CUDA module load."
        );
        assert!(
            EMIT_ARTIFACT_LOADER.contains("validate_buffer_table(&manifest.buffers)")
                && EMIT_ARTIFACT_LOADER.contains("both use binding")
                && EMIT_ARTIFACT_LOADER.contains("metrics records are u32 words"),
            "Fix: generated launchers must enforce the manifest buffer ABI before CUDA allocation."
        );
        assert!(
            EMIT_ARTIFACT_LOADER.contains("validate_sha256_manifest_field(\"kernel\"")
                && EMIT_ARTIFACT_LOADER.contains("vsa_fingerprint"),
            "Fix: generated launchers must preflight digest fields and semantic fingerprints."
        );
    }
}
